version: 2.1

jobs:
  build:
    docker:
      - image: http-reverse
        auth:
          username: cgik
          password: $GITHUB_TOKEN
    steps:
      - run: docker build . -t ghcr.io/cgik/http-reverse:latest
      - run: docker push ghcr.io/cgik/http-reverse:latest