version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ghcr.io/cgik/http-reverse
      GITHUB_NAME: cgik
    docker:
      - image: cimg/base:2022.06-22.04

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build Image
          command: docker build . -t $IMAGE_NAME:latest
  
  publish:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run: 
          name: Publish Image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$GITHUB_TOKEN"
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push:
          requires:
            - build
        filters:
          branches:
            only: main